name: Kotlin CI

on: [push, pull_request]

jobs:
  test_ubuntu:
    name: Test build on latest Ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Detekt all
        uses: natiginfo/action-detekt-all@1.13.0

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Gradle
        run: ./gradlew clean build
